// <auto-generated />
using System;
using FoodSafetyTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodSafetyTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321093424_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FoodSafetyTracker.Models.FollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InspectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.ToTable("FollowUps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClosedDate = new DateTime(2025, 12, 1, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            DueDate = new DateTime(2025, 11, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            InspectionId = 2,
                            Notes = "Cold storage repaired and verified.",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            ClosedDate = new DateTime(2025, 12, 26, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            DueDate = new DateTime(2025, 12, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            InspectionId = 3,
                            Notes = "Separation protocols implemented.",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            ClosedDate = new DateTime(2026, 1, 29, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            DueDate = new DateTime(2026, 1, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            InspectionId = 6,
                            Notes = "Pest control contractor report submitted.",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            DueDate = new DateTime(2026, 2, 19, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            InspectionId = 9,
                            Notes = "Handwashing facilities replacement pending.",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            DueDate = new DateTime(2026, 3, 1, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            InspectionId = 11,
                            Notes = "Pest control contract not yet signed.",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            DueDate = new DateTime(2026, 3, 11, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            InspectionId = 15,
                            Notes = "Storage unit replacement ordered.",
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            DueDate = new DateTime(2026, 3, 18, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            InspectionId = 23,
                            Notes = "Deep clean and pest exclusion required.",
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            DueDate = new DateTime(2026, 3, 28, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            InspectionId = 23,
                            Notes = "Staff food hygiene training scheduled.",
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            DueDate = new DateTime(2026, 4, 4, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            InspectionId = 15,
                            Notes = "Re-inspection scheduled for next month.",
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            ClosedDate = new DateTime(2026, 3, 1, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            DueDate = new DateTime(2026, 2, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            InspectionId = 9,
                            Notes = "Interim fix verified by inspector.",
                            Status = 1
                        });
                });

            modelBuilder.Entity("FoodSafetyTracker.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PremisesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PremisesId");

                    b.ToTable("Inspections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InspectionDate = new DateTime(2025, 9, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Excellent hygiene standards.",
                            Outcome = 0,
                            PremisesId = 1,
                            Score = 92
                        },
                        new
                        {
                            Id = 2,
                            InspectionDate = new DateTime(2025, 10, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Inadequate cold storage temperatures.",
                            Outcome = 1,
                            PremisesId = 2,
                            Score = 55
                        },
                        new
                        {
                            Id = 3,
                            InspectionDate = new DateTime(2025, 10, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Cross-contamination risks identified.",
                            Outcome = 1,
                            PremisesId = 3,
                            Score = 48
                        },
                        new
                        {
                            Id = 4,
                            InspectionDate = new DateTime(2025, 11, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Good overall, minor paperwork issues.",
                            Outcome = 0,
                            PremisesId = 4,
                            Score = 88
                        },
                        new
                        {
                            Id = 5,
                            InspectionDate = new DateTime(2025, 11, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Satisfactory.",
                            Outcome = 0,
                            PremisesId = 5,
                            Score = 76
                        },
                        new
                        {
                            Id = 6,
                            InspectionDate = new DateTime(2025, 12, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Rodent evidence found in storeroom.",
                            Outcome = 1,
                            PremisesId = 6,
                            Score = 41
                        },
                        new
                        {
                            Id = 7,
                            InspectionDate = new DateTime(2025, 12, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Outstanding. No issues.",
                            Outcome = 0,
                            PremisesId = 7,
                            Score = 95
                        },
                        new
                        {
                            Id = 8,
                            InspectionDate = new DateTime(2026, 1, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Pass with recommendations.",
                            Outcome = 0,
                            PremisesId = 8,
                            Score = 63
                        },
                        new
                        {
                            Id = 9,
                            InspectionDate = new DateTime(2026, 1, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Handwashing facilities non-compliant.",
                            Outcome = 1,
                            PremisesId = 9,
                            Score = 52
                        },
                        new
                        {
                            Id = 10,
                            InspectionDate = new DateTime(2026, 1, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Good standards maintained.",
                            Outcome = 0,
                            PremisesId = 10,
                            Score = 84
                        },
                        new
                        {
                            Id = 11,
                            InspectionDate = new DateTime(2026, 2, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Critical violations — pest control.",
                            Outcome = 1,
                            PremisesId = 11,
                            Score = 38
                        },
                        new
                        {
                            Id = 12,
                            InspectionDate = new DateTime(2026, 2, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Adequate, staff training recommended.",
                            Outcome = 0,
                            PremisesId = 12,
                            Score = 71
                        },
                        new
                        {
                            Id = 13,
                            InspectionDate = new DateTime(2026, 2, 21, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Follow-up: still excellent.",
                            Outcome = 0,
                            PremisesId = 1,
                            Score = 90
                        },
                        new
                        {
                            Id = 14,
                            InspectionDate = new DateTime(2026, 2, 24, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Cold storage now fixed.",
                            Outcome = 0,
                            PremisesId = 2,
                            Score = 68
                        },
                        new
                        {
                            Id = 15,
                            InspectionDate = new DateTime(2026, 3, 1, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Still non-compliant on storage.",
                            Outcome = 1,
                            PremisesId = 3,
                            Score = 59
                        },
                        new
                        {
                            Id = 16,
                            InspectionDate = new DateTime(2026, 3, 3, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Paperwork now in order.",
                            Outcome = 0,
                            PremisesId = 4,
                            Score = 91
                        },
                        new
                        {
                            Id = 17,
                            InspectionDate = new DateTime(2026, 3, 6, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Consistent performance.",
                            Outcome = 0,
                            PremisesId = 5,
                            Score = 80
                        },
                        new
                        {
                            Id = 18,
                            InspectionDate = new DateTime(2026, 3, 9, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Pest issue resolved.",
                            Outcome = 0,
                            PremisesId = 6,
                            Score = 66
                        },
                        new
                        {
                            Id = 19,
                            InspectionDate = new DateTime(2026, 3, 11, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Exemplary.",
                            Outcome = 0,
                            PremisesId = 7,
                            Score = 97
                        },
                        new
                        {
                            Id = 20,
                            InspectionDate = new DateTime(2026, 3, 13, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Improvements noted.",
                            Outcome = 0,
                            PremisesId = 8,
                            Score = 74
                        },
                        new
                        {
                            Id = 21,
                            InspectionDate = new DateTime(2026, 3, 15, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Handwashing facilities upgraded.",
                            Outcome = 0,
                            PremisesId = 9,
                            Score = 70
                        },
                        new
                        {
                            Id = 22,
                            InspectionDate = new DateTime(2026, 3, 16, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Consistent high standard.",
                            Outcome = 0,
                            PremisesId = 10,
                            Score = 88
                        },
                        new
                        {
                            Id = 23,
                            InspectionDate = new DateTime(2026, 3, 17, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Partial improvement, still failing.",
                            Outcome = 1,
                            PremisesId = 11,
                            Score = 45
                        },
                        new
                        {
                            Id = 24,
                            InspectionDate = new DateTime(2026, 3, 18, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "Good progress.",
                            Outcome = 0,
                            PremisesId = 12,
                            Score = 83
                        },
                        new
                        {
                            Id = 25,
                            InspectionDate = new DateTime(2026, 3, 19, 9, 34, 23, 726, DateTimeKind.Utc).AddTicks(1795),
                            Notes = "All cleared.",
                            Outcome = 0,
                            PremisesId = 6,
                            Score = 78
                        });
                });

            modelBuilder.Entity("FoodSafetyTracker.Models.Premises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Premises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 High St",
                            Name = "The Golden Fork",
                            RiskRating = 0,
                            Town = "Dorchester"
                        },
                        new
                        {
                            Id = 2,
                            Address = "34 Market Sq",
                            Name = "Burger Palace",
                            RiskRating = 1,
                            Town = "Dorchester"
                        },
                        new
                        {
                            Id = 3,
                            Address = "5 Harbour Rd",
                            Name = "Sea Breeze Fish & Chips",
                            RiskRating = 2,
                            Town = "Dorchester"
                        },
                        new
                        {
                            Id = 4,
                            Address = "78 Church Lane",
                            Name = "Mama's Italian Kitchen",
                            RiskRating = 0,
                            Town = "Dorchester"
                        },
                        new
                        {
                            Id = 5,
                            Address = "2 Station Rd",
                            Name = "Sunrise Cafe",
                            RiskRating = 1,
                            Town = "Weymouth"
                        },
                        new
                        {
                            Id = 6,
                            Address = "19 Pier Approach",
                            Name = "The Rusty Anchor",
                            RiskRating = 2,
                            Town = "Weymouth"
                        },
                        new
                        {
                            Id = 7,
                            Address = "45 Park Ave",
                            Name = "Green Garden Deli",
                            RiskRating = 0,
                            Town = "Weymouth"
                        },
                        new
                        {
                            Id = 8,
                            Address = "7 Broadway",
                            Name = "Hot Wok Express",
                            RiskRating = 1,
                            Town = "Weymouth"
                        },
                        new
                        {
                            Id = 9,
                            Address = "1 Kings Rd",
                            Name = "The Crown Pub",
                            RiskRating = 1,
                            Town = "Bridport"
                        },
                        new
                        {
                            Id = 10,
                            Address = "22 West St",
                            Name = "Bridport Bakery",
                            RiskRating = 0,
                            Town = "Bridport"
                        },
                        new
                        {
                            Id = 11,
                            Address = "88 South St",
                            Name = "Spice Route",
                            RiskRating = 2,
                            Town = "Bridport"
                        },
                        new
                        {
                            Id = 12,
                            Address = "3 Cliff Road",
                            Name = "Coastline Catering",
                            RiskRating = 1,
                            Town = "Bridport"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FoodSafetyTracker.Models.FollowUp", b =>
                {
                    b.HasOne("FoodSafetyTracker.Models.Inspection", "Inspection")
                        .WithMany("FollowUps")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("FoodSafetyTracker.Models.Inspection", b =>
                {
                    b.HasOne("FoodSafetyTracker.Models.Premises", "Premises")
                        .WithMany("Inspections")
                        .HasForeignKey("PremisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Premises");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodSafetyTracker.Models.Inspection", b =>
                {
                    b.Navigation("FollowUps");
                });

            modelBuilder.Entity("FoodSafetyTracker.Models.Premises", b =>
                {
                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
